/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formulariocdm;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaIJTheme;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
        int xMouse;
        int yMouse;
        public Formulario() {
            initComponents();
            nombre.setText("Eva Marie");
            email.setText("email@dominio.es");
            contrasena.setText("********");
            registrarBoton.putClientProperty( "FlatLaf.style", "arc:0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        barraArriba = new javax.swing.JPanel();
        fondoCerrar = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        registrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(792, 546));

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.login-2.png"))); // NOI18N
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 60));

        labelUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelUsuario.setText("email");
        jPanel2.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 320, -1));

        labelContrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelContrasena.setText("Contraseña");
        jPanel2.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        contrasena.setForeground(new java.awt.Color(153, 153, 153));
        contrasena.setBorder(null);
        contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaMousePressed(evt);
            }
        });
        contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contrasenaKeyPressed(evt);
            }
        });
        jPanel2.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 320, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 320, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 320, 10));

        barraArriba.setBackground(new java.awt.Color(255, 255, 255));
        barraArriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraArribaMouseDragged(evt);
            }
        });
        barraArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraArribaMousePressed(evt);
            }
        });

        fondoCerrar.setBackground(new java.awt.Color(255, 255, 255));

        cerrar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        cerrar.setForeground(new java.awt.Color(51, 51, 51));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoCerrarLayout = new javax.swing.GroupLayout(fondoCerrar);
        fondoCerrar.setLayout(fondoCerrarLayout);
        fondoCerrarLayout.setHorizontalGroup(
            fondoCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoCerrarLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fondoCerrarLayout.setVerticalGroup(
            fondoCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraArribaLayout = new javax.swing.GroupLayout(barraArriba);
        barraArriba.setLayout(barraArribaLayout);
        barraArribaLayout.setHorizontalGroup(
            barraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraArribaLayout.createSequentialGroup()
                .addComponent(fondoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        barraArribaLayout.setVerticalGroup(
            barraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraArribaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(barraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 320, 10));

        nombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreMousePressed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 320, -1));

        labelNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNombre.setText("nombre");
        jPanel2.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        registrarBoton.setText("REGISTRAR");
        registrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBotonActionPerformed(evt);
            }
        });
        jPanel2.add(registrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, 50));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -400;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        if (email.getText().equals("email@dominio.es")) {
            email.setText("");
            email.setForeground(Color.white);
        }

        if(String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText("********");
            contrasena.setForeground(Color.gray);
        }
        
        if (nombre.getText().isEmpty()){
            nombre.setText("Eva Marie");
            nombre.setForeground(Color.gray);
        }
    }//GEN-LAST:event_emailMousePressed

    private void contrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaMousePressed
        if (String.valueOf(contrasena.getPassword()).equals("********")) {
            contrasena.setText("");
            contrasena.setForeground(Color.white);
        }

        if (email.getText().isEmpty()){
            email.setText("email@dominio.es");
            email.setForeground(Color.gray);
        }
        
        if (nombre.getText().isEmpty()){
            nombre.setText("Eva Marie");
            nombre.setForeground(Color.gray);
        }
    }//GEN-LAST:event_contrasenaMousePressed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        fondoCerrar.setBackground(Color.PINK);
        cerrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        fondoCerrar.setBackground(Color.WHITE);
        cerrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarMouseExited

    private void barraArribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraArribaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_barraArribaMouseDragged

    private void barraArribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraArribaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraArribaMousePressed

    private void nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMousePressed
        if (String.valueOf(nombre.getText()).equals("Eva Marie")) {
            nombre.setText("");
            nombre.setForeground(Color.white);
        }

        if (email.getText().isEmpty()){
            email.setText("email@dominio.es");
            email.setForeground(Color.gray);
        }
        
        if(String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText("********");
            contrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreMousePressed

    private void registrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBotonActionPerformed
        performLogin();
    }//GEN-LAST:event_registrarBotonActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // Si la tecla pulsada es enter
            if (email.getText().equals("email@dominio.es")) {
            email.setText("");
            email.setForeground(Color.white);
        }

        if(String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText("********");
            contrasena.setForeground(Color.gray);
        }
        
        if (nombre.getText().isEmpty()){
            nombre.setText("Eva Marie");
            nombre.setForeground(Color.gray);
        }
        email.requestFocus(); //Pasar a email
    }
        
    }//GEN-LAST:event_nombreKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // Si la tecla pulsada es enter
            if (String.valueOf(contrasena.getPassword()).equals("********")) {
            contrasena.setText("");
            contrasena.setForeground(Color.white);
        }

        if (email.getText().isEmpty()){
            email.setText("email@dominio.es");
            email.setForeground(Color.gray);
        }
        
        if (nombre.getText().isEmpty()){
            nombre.setText("Eva Marie");
            nombre.setForeground(Color.gray);
        }
        contrasena.requestFocus(); //Pasar a contraseña
    }
        
    }//GEN-LAST:event_emailKeyPressed

    private void contrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contrasenaKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // Si la tecla pulsada es enter
             if (String.valueOf(nombre.getText()).equals("Eva Marie")) {
            nombre.setText("");
            nombre.setForeground(Color.white);
        }

        if (email.getText().isEmpty()){
            email.setText("email@dominio.es");
            email.setForeground(Color.gray);
        }
        
        if(String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText("********");
            contrasena.setForeground(Color.gray);
        }
        performLogin(); //Hacer el método del Login (El que se haría al pulsar el botón)
    }
         
    }//GEN-LAST:event_contrasenaKeyPressed
    //Método para el Login
    private void performLogin() {
    if (String.valueOf(contrasena.getPassword()).equals("hola") && email.getText().equals("Abu") && nombre.getText().equals("Barbara"))  {
        JOptionPane.showMessageDialog(null, "¡Bienvenido!");
    } else {
        JOptionPane.showMessageDialog(null, "Contraseña o usuario incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDraculaIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario form = new Formulario();
            form.setVisible(true);
            form.requestFocusInWindow();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraArriba;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField email;
    private javax.swing.JPanel fondoCerrar;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton registrarBoton;
    // End of variables declaration//GEN-END:variables
    
}
